

# docker build -t my-html-server .
# docker run -d -p 8080:8080 my-html-server

version: '3'
services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - "./mosquitto.conf:/mosquitto/mosquitto.conf"
    ports:
      - 1883:1883

  nginx:
    image: nginx:latest
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./certs:/etc/nginx/ssl"

    ports:
      - "443:443"
    depends_on:
      - mosquitto

