

# docker build -t my-html-server .
# docker run -d -p 8080:8080 my-html-server

version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./certs:/etc/nginx/ssl"

    ports:
      - "443:443"


